# Generated by Django 3.2.4 on 2021-06-14 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='users',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто отправил заявку'),
        ),
    ]
