# Generated by Django 3.2.4 on 2021-06-14 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_booking_userss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='userss',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто забронировал'),
        ),
    ]
